version: v0.9.1+{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
skip_branch_with_pr: true
image: Visual Studio 2017
clone_depth: 100
install:
- cmd: |
    set PATH=%PATH%;C:\Program Files (x86)\WiX Toolset v3.11\bin
    set GOPATH=C:\Users\appveyor
    set PATH=%PATH%;%GOPATH%\bin
    go get "github.com/Masterminds/semver"
    pip install sphinx sphinx_rtd_theme pyyaml

build_script:
- ps: |
    go version
    #$ErrorActionPreference = "Stop";
    $env:BUILD_VERSION=$env:APPVEYOR_BUILD_VERSION
    $env:MSI_VERSION=$(go run .\src\installer\semver-to-msiversion.go "${env:APPVEYOR_BUILD_VERSION}" "${env:APPVEYOR_BUILD_NUMBER}")
    $GOPROXY="direct";
    & {
      $ErrorActionPreference = 'SilentlyContinue'
      .\release-build.cmd 2>&1
    }

test: off
artifacts:
- path: build\DCS-BIOS-Hub-Setup-${build_version}.msi
  name: MsiInstaller
deploy:
- provider: GitHub
  description: DCS-BIOS Release
  auth_token:
    secure: 23xmGoTKygMQyZ+Jtf+CF+wtN8EMABOIPH3ruy5E2ROY2weXbjZAhJ/MZOh8ZuQs
  artifact: MsiInstaller
  draft: true
  on:
    branch: master
